//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace bizmar

{
    using System;
    using System.Collections.Generic;
    
    public partial class sayac
    {
        public int sayacNo { get; set; }
        public int urunKodu { get; set; }
        public int urunSayaci { get; set; }
    
        public virtual urun urun { get; set; }
    }
}
