//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizmar
{
    using System;
    using System.Collections.Generic;
    
    public partial class todeme
    {
        public int todemeNo { get; set; }
        public int odenenTutar { get; set; }
        public System.DateTime odenenTarih { get; set; }
        public int tNo { get; set; }
    
        public virtual tedarikci tedarikci { get; set; }
    }
}
