//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Satış
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun
    {
        public int urunKodu { get; set; }
        public string barkodNo { get; set; }
        public int stokMiktari { get; set; }
        public double satisFiyati { get; set; }
        public string urunAd { get; set; }
    }
}
