//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliyeUrunu
    {
        public int iuNo { get; set; }
        public string iuBarkodNo { get; set; }
        public string iuAd { get; set; }
        public int iuMiktar { get; set; }
        public double iuFiyat { get; set; }
        public int irsaliyeNo { get; set; }
    
        public virtual irsaliye irsaliye { get; set; }
    }
}
