//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizmar.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class irsaliye
    {
        public int irsaliyeNo { get; set; }
        public System.DateTime irsaliyeTarih { get; set; }
        public double irsaliyeTutar { get; set; }
        public Nullable<int> ulNo { get; set; }
        public Nullable<int> tNo { get; set; }
    
        public virtual tedarikci tedarikci { get; set; }
        public virtual urunListesi urunListesi { get; set; }
    }
}
