//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bizmar.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pesinSatis
    {
        public int psNo { get; set; }
        public System.DateTime psTarih { get; set; }
        public double psTutar { get; set; }
        public Nullable<int> ulNo { get; set; }
    
        public virtual urunListesi urunListesi { get; set; }
    }
}
